openai:
  api_key: "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"
  embedding_model: "text-embedding-3-small"
  llm_model: "gpt-4o-mini"

chroma:
  persist_directory: "data/processed/chroma_db"  # Directory to store Chroma data